---
title: "Cleaning & Wrangling"
author: "Brooke Wainwright"
format: html
editor: visual
---

## Background
These data come from a common garden drought experiment in Davis, California investigating the functional trait strategies of California grassland plants from five different grassland communities spanning California's latitudinal precipitation gradient. There 10-12 species per community or provenance, each provenance has 16 plots (8 drought, 8 control) across 10 shelters (5 drought, 5 control). In the 2022-2023, we focused on collecting whole plant traits, inclduing reproductive investment. This study focuses on how these traits relate to reproductive investment depending on drought treatment, native status, or where the plant is from. This document will clean and wrangle the many datasets and images associated with this study. 

## Traits & Objectives
Reproductive allocation & End of Season biomass
Relative Growth Rate
Photosynthetic Rate
Leaf Mass Area
Leaf Area
WUE
Height
Leaf Nitrogen
Date of first flower
Mid season biomass partial
Root biomass partial
Root:shoot ratio partial
Root diameter partial
Specific root length partial
Root nitrogen partial

Bring in, explore, clean, rectify outliers, organize each trait or group of traits and export as "..._CLEAN"

## Setup
```{r}
#| message: false
#| warning: false
#| echo: false

library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
```

## Reproductive allocation & End of Season biomass

## Relative Growth Rate

## Photosynthetic Rate

## Leaf Mass Area

## Leaf Area

## WUE

## Height

## Leaf Nitrogen

## Date of first flower

## Mid season biomass partial

## Root biomass partial

## Root:shoot ratio partial

## Root diameter partial

## Specific root length partial

## Root nitrogen partial

